name: Gatling CI

on:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        command:
          - 'mvn gatling:test -Dgatling.simulationClass=simulations.GetProduct'
          - 'mvn gatling:test -Dgatling.simulationClass=simulations.DeleteProduct'
          - 'mvn gatling:test -Dgatling.simulationClass=simulations.PostProduct'
          - 'mvn gatling:test -Dgatling.simulationClass=simulations.PutProduct'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'

      - name: Run Gatling tests
        run: ${{ matrix.command }}

      - name: Set Artifact ID
        run: echo "ARTIFACT_ID=$(date +%s)" >> $GITHUB_ENV

      - name: Debug Gatling Reports
        run: ls -R target/gatling/ || echo "No reports found"

      - name: Upload Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: report-load-${{ env.ARTIFACT_ID }}
          path: target/gatling/**
          retention-days: 1
